#!/bin/sh

#SBATCH --job-name=u2145461-
#SBATCH --partition=Gecko  
#SBATCH --cpus-per-task=6
#SBATCH --mem-per-cpu=4G
#SBATCH --gres=gpu:1
#SBATCH --time=480:00
#SBATCH --output=%j/cs310_output_%j.out
#SBATCH --error=%j/cs310_error_%j.err

echo ===== ENVIRONMENT =====

. /etc/profile.d/modules.sh
echo ===== CUDA INFO =====

echo CUDA 12.3


echo ===== COMPILER INFO =====

echo GCC 12.2.0

echo ===== CPU INFO =====

lscpu

echo ===== GPU INFO =====

lshw -C display

echo ===== GPU INFO NVIDIA-SMI =====

nvidia-smi

echo ===== RUNNING ON kudu =====

#############################################################################
# Want to add your own environment variables to the program? Add them here! #

#############################################################################
echo

